version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../backend/media/:/usr/share/nginx/html/media/ # TODO: set container
      - ../backend/static/admin/:/usr/share/nginx/html/static/admin/ # TODO: set container
      - ../backend/static/rest_framework/:/usr/share/nginx/html/static/rest_framework/ # TODO: set container
