# Generated by Django 2.2.16 on 2022-08-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_auto_20220806_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                to="food.Tag",
                verbose_name="Тег",
            ),
        ),
    ]
