# Generated by Django 2.2.16 on 2022-08-08 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0005_auto_20220806_1718"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["-id"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
