# Generated by Django 2.2.16 on 2022-08-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0007_auto_20220808_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_in_recipe",
                to="food.Ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_in_recipe",
                to="food.Recipe",
            ),
        ),
    ]
