# Generated by Django 2.2.16 on 2022-08-06 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20220806_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cart",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_added_to_cart",
                to="food.Recipe",
                verbose_name="Находится ли в корзине",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="favorite",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_favorited",
                to="food.Recipe",
                verbose_name="Находится ли в избранном",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="follower",
            field=models.ManyToManyField(
                blank=True,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
    ]
