# Generated by Django 2.2.16 on 2022-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20220806_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="Email"
            ),
        ),
    ]
